title: "Miguel Cardoso"
author: ""
description: ""
email: ""
permalink: /:title/ 
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_frame: true           # adds a gray frame to the site
show_excerpts: true        # show article excerpts on the home page
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
#  - {file: "cardoso.pdf", tile: "CV", icon: home}
#  - {title: "Lab", url: ""}
#  - {file: "home.md", title: "Home", icon: home} 
#  - {title: "About me", icon: user, url: "https://miguelangelooscardoso.github.io/markdown-cv/"}
  - {file: "cover.md", title: "about me"} # address-card
# Font Awesome Icon List
# https://aksakalli.github.io/jekyll-doc-theme/docs/font-awesome/

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:cardosomiguel@ua.pt"}
#  - {title: Twitter, icon: twitter, url: "https://miguelangelooscardoso.github.io/nyancat"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/miguelangelooscardoso/"}
  - {title: Github, icon: github, url: "https://github.com/miguelangelooscardoso"}
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 
